### ISSUE TITLE
Estruturação de pastas.

### ISSUE THREAD

**Issue by fvieir** [TStavale/Landing_page#1]
Fala Tassio, como vai?

Conforme deixado o Feedback e orientações no Discord, segue minha solicitação para estruturação de pastas.

Qualquer duvida é so chamar.

Forte abraço.

**Comment by TStavale** [comment]
Fala Fabricio... 

Reorganizei as pastas e corrigi a margin como orientado. 
Obrigado pelo feedback. 

Grande abraço!
